function menuAdmin() {
    return [
        {
            label: 'users',
            id: 1,
            icon: 'lar la-user',
            iconColor: 'amber',
            expandable: true,
            children: [
                {
                    label: 'users',
                    id: 11,
                    url: '/api/v1/user',
                    children: [],
                    icon: 'arrow_right_alt',
                    iconColor: 'amber-2',
                },
                {
                    label: 'roles',
                    id: 12,
                    children: [],
                    url: '/api/v1/role/pages',
                    icon: 'arrow_right_alt',
                    iconColor: 'amber-2',
                },
            ],
        },
        {
            label: 'mat_chars',
            id: 2,
            icon: 'las la-shapes',
            iconColor: 'amber',
            expandable: true,
            children: [
                {
                    label: 'hdsc',
                    id: 21,
                    url: '/api/v1/handbook/hs/pages',
                    children: [],
                    icon: 'arrow_right_alt',
                    iconColor: 'amber-2',
                },
                {
                    label: 'hdcm',
                    id: 22,
                    children: [],
                    url: '/api/v1/handbook/ch/pages',
                    icon: 'arrow_right_alt',
                    iconColor: 'amber-2',
                },
                {
                    label: 'mattype',
                    id: 23,
                    url: '/api/v1/handbook/mattype/pages',
                    children: [],
                    icon: 'arrow_right_alt',
                    iconColor: 'amber-2',
                },
                {
                    label: 'imitmat',
                    id: 24,
                    url: '/api/v1/handbook/imitmat/pages',
                    children: [],
                    icon: 'arrow_right_alt',
                    iconColor: 'amber-2',
                },
                {
                    label: 'chemresist',
                    id: 25,
                    url: '/api/v1/handbook/chemresist/pages',
                    children: [],
                    icon: 'arrow_right_alt',
                    iconColor: 'amber-2',
                },
            ],
        },
        {
            label: 'misc',
            id: 3,
            icon: 'las la-industry',
            iconColor: 'amber',
            expandable: true,
            children: [
                {
                    label: 'companies',
                    id: 31,
                    url: '​/api​/v1​/handbook​/toolmanufacturers/pages',
                    children: [],
                    icon: 'arrow_right_alt',
                    iconColor: 'amber-2',
                },
                {
                    label: 'toolclass',
                    id: 32,
                    url: '/api/v1/handbook/toolclass/pages',
                    children: [],
                    icon: 'arrow_right_alt',
                    iconColor: 'amber-2',
                },
                {
                    label: 'tooltypes',
                    id: 33,
                    url: '/api/v1/handbook/tooltypes/pages',
                    children: [],
                    icon: 'arrow_right_alt',
                    iconColor: 'amber-2',
                },
                {
                    label: 'typetech',
                    id: 34,
                    url: '/api/v1/handbook/typetechnologies/pages',
                    children: [],
                    icon: 'arrow_right_alt',
                    iconColor: 'amber-2',
                },
                {
                    label: 'tech',
                    id: 35,
                    url: '/api/v1/handbook/technology/pages',
                    children: [],
                    icon: 'arrow_right_alt',
                    iconColor: 'amber-2',
                },
                {
                    label: 'measuring-st',
                    id: 36,
                    url: '/api/v1/handbook/measuring-standarts/pages',
                    children: [],
                    icon: 'arrow_right_alt',
                    iconColor: 'amber-2',
                },
                {
                    label: 'color',
                    id: 37,
                    url: '/api/v1/handbook/colors',
                    children: [],
                    icon: 'arrow_right_alt',
                    iconColor: 'amber-2',
                },
                {
                    label: 'statuses',
                    id: 38,
                    url: '/api/v1/handbook/status/pages',
                    children: [],
                    icon: 'arrow_right_alt',
                    iconColor: 'amber-2',
                },
            ],
        },
    ]
}

export default menuAdmin
