function menuAdmin() {
    return [
        {
            label: 'users',
            id: 1,
            icon: 'lar la-user',
            iconColor: 'amber',
            expandable: true,
            selectable: true,
            children: [
                {
                    label: 'users',
                    id: 11,
                    url: '/users',
                    children: [],
                    icon: 'arrow_right_alt',
                    iconColor: 'amber-2',
                    selectable: true,
                },
                {
                    label: 'roles',
                    id: 12,
                    children: [],
                    url: '/roles',
                    icon: 'arrow_right_alt',
                    iconColor: 'amber-2',
                    selectable: true,
                },
            ],
        },
        {
            label: 'mat_chars',
            id: 2,
            icon: 'las la-shapes',
            iconColor: 'amber',
            expandable: true,
            selectable: true,
            children: [
                {
                    label: 'hdsc',
                    id: 21,
                    url: '/hardness-scales',
                    children: [],
                    icon: 'arrow_right_alt',
                    iconColor: 'amber-2',
                    selectable: true,
                },
                {
                    label: 'hdcm',
                    id: 22,
                    children: [],
                    url: '/common-hardness',
                    icon: 'arrow_right_alt',
                    iconColor: 'amber-2',
                    selectable: true,
                },
                {
                    label: 'mattype',
                    id: 23,
                    url: '/material-types',
                    children: [],
                    icon: 'arrow_right_alt',
                    iconColor: 'amber-2',
                    selectable: true,
                },
                {
                    label: 'imitmat',
                    id: 24,
                    url: '/imitation-materials',
                    children: [],
                    icon: 'arrow_right_alt',
                    iconColor: 'amber-2',
                    selectable: true,
                },
                {
                    label: 'chemresist',
                    id: 25,
                    url: '/chemical-resistance',
                    children: [],
                    icon: 'arrow_right_alt',
                    iconColor: 'amber-2',
                    selectable: true,
                },
            ],
        },
        {
            label: 'misc',
            id: 3,
            icon: 'las la-industry',
            iconColor: 'amber',
            expandable: true,
            selectable: true,
            children: [
                {
                    label: 'companies',
                    id: 31,
                    url: '​/companies',
                    children: [],
                    icon: 'arrow_right_alt',
                    iconColor: 'amber-2',
                    selectable: true,
                },
                {
                    label: 'toolclass',
                    id: 32,
                    url: '/tool-classes',
                    children: [],
                    icon: 'arrow_right_alt',
                    iconColor: 'amber-2',
                    selectable: true,
                },
                {
                    label: 'tooltypes',
                    id: 33,
                    url: '/tool-types',
                    children: [],
                    icon: 'arrow_right_alt',
                    iconColor: 'amber-2',
                    selectable: true,
                },
                {
                    label: 'typetech',
                    id: 34,
                    url: '/technology-types',
                    children: [],
                    icon: 'arrow_right_alt',
                    iconColor: 'amber-2',
                    selectable: true,
                },
                {
                    label: 'tech',
                    id: 35,
                    url: '/technology',
                    children: [],
                    icon: 'arrow_right_alt',
                    iconColor: 'amber-2',
                    selectable: true,
                },
                {
                    label: 'measuring-st',
                    id: 36,
                    url: '/measuring-standarts',
                    children: [],
                    icon: 'arrow_right_alt',
                    iconColor: 'amber-2',
                    selectable: true,
                },
                {
                    label: 'color',
                    id: 37,
                    url: '/colors',
                    children: [],
                    icon: 'arrow_right_alt',
                    iconColor: 'amber-2',
                    selectable: true,
                },
                {
                    label: 'statuses',
                    id: 38,
                    url: '/statuses',
                    children: [],
                    icon: 'arrow_right_alt',
                    iconColor: 'amber-2',
                    selectable: true,
                },
            ],
        },
    ]
}

export default menuAdmin
